"""Build a standalone GitHub Pages preview; never include research records."""
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from server.buffet_server import DEFAULT_CONFIG


def build(output=None):
    output = Path(output) if output else ROOT / '_site'
    if output.exists():
        raise SystemExit(f'Build directory already exists: {output}. Remove it before rebuilding.')
    shutil.copytree(ROOT / 'web', output, ignore=shutil.ignore_patterns('*.meta', '.DS_Store'))
    conditions = json.loads((ROOT / 'study/conditions.json').read_text())
    settings = {name: dict(DEFAULT_CONFIG, **values) for name, values in conditions.items()}
    for name, config in settings.items():
        config.update(condition=name, allowedParentOrigins=[], apiBaseUrl='', parentOrigin='')
    (output / 'src/deployment.js').write_text(
        '// Generated by tools/build_pages.py. This preview saves on this device only.\n'
        + 'export const deployment = ' + json.dumps({'storage': 'local', 'conditions': settings}, indent=2) + ';\n'
    )
    (output / '.nojekyll').touch()
    shutil.copy2(ROOT / 'THIRD_PARTY.md', output / 'THIRD_PARTY.md')
    print(f'Built standalone preview: {output}')
    return output


if __name__ == '__main__':
    build()
